export const currentUser = {
  id: "user_1",
  name: "John Doe",
  email: "john@example.com",
};

export const itemTypes = [
  { id: "type_snippet", name: "Snippet", icon: "Code", color: "#3b82f6", isSystem: true, slug: "snippets" },
  { id: "type_prompt", name: "Prompt", icon: "Sparkles", color: "#8b5cf6", isSystem: true, slug: "prompts" },
  { id: "type_command", name: "Command", icon: "Terminal", color: "#f97316", isSystem: true, slug: "commands" },
  { id: "type_note", name: "Note", icon: "StickyNote", color: "#fde047", isSystem: true, slug: "notes" },
  { id: "type_file", name: "File", icon: "File", color: "#6b7280", isSystem: true, slug: "files" },
  { id: "type_image", name: "Image", icon: "ImageIcon", color: "#ec4899", isSystem: true, slug: "images" },
  { id: "type_link", name: "Link", icon: "Link", color: "#10b981", isSystem: true, slug: "links" },
];

export const collections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    itemCount: 12,
    dominantTypeId: "type_snippet",
  },
  {
    id: "col_2",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    itemCount: 8,
    dominantTypeId: "type_snippet",
  },
  {
    id: "col_3",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    itemCount: 5,
    dominantTypeId: "type_file",
  },
  {
    id: "col_4",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: false,
    itemCount: 24,
    dominantTypeId: "type_snippet",
  },
  {
    id: "col_5",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    itemCount: 15,
    dominantTypeId: "type_command",
  },
  {
    id: "col_6",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    itemCount: 18,
    dominantTypeId: "type_prompt",
  },
];

export const items = [
  {
    id: "item_1",
    title: "useAuth Hook",
    description: "Custom authentication hook for React applications",
    contentType: "text",
    content: "export function useAuth() {\n  // ...\n}",
    typeId: "type_snippet",
    isFavorite: true,
    isPinned: true,
    language: "typescript",
    tags: ["react", "auth", "hooks"],
    collectionId: "col_1",
    createdAt: "2026-01-15",
  },
  {
    id: "item_2",
    title: "API Error Handling Pattern",
    description: "Fetch wrapper with exponential backoff retry logic",
    contentType: "text",
    content: "async function fetchWithRetry(url, options, retries = 3) {\n  // ...\n}",
    typeId: "type_snippet",
    isFavorite: false,
    isPinned: true,
    language: "typescript",
    tags: ["api", "error-handling", "fetch"],
    collectionId: "col_1",
    createdAt: "2026-01-12",
  },
  {
    id: "item_3",
    title: "Git Stash Workflow",
    description: "Save and restore work in progress",
    contentType: "text",
    content: "git stash push -m 'WIP: feature'",
    typeId: "type_command",
    isFavorite: false,
    isPinned: false,
    language: null,
    tags: ["git", "workflow"],
    collectionId: "col_5",
    createdAt: "2026-01-10",
  },
  {
    id: "item_4",
    title: "Code Review Prompt",
    description: "Prompt for thorough code reviews",
    contentType: "text",
    content: "Review the following code for bugs, performance issues, and best practices...",
    typeId: "type_prompt",
    isFavorite: true,
    isPinned: false,
    language: null,
    tags: ["ai", "code-review"],
    collectionId: "col_6",
    createdAt: "2026-01-08",
  },
  {
    id: "item_5",
    title: "Python List Comprehension",
    description: "Common list comprehension patterns",
    contentType: "text",
    content: "squares = [x**2 for x in range(10) if x % 2 == 0]",
    typeId: "type_snippet",
    isFavorite: false,
    isPinned: false,
    language: "python",
    tags: ["python", "list"],
    collectionId: "col_2",
    createdAt: "2026-01-05",
  },
];

export const typeCounts: Record<string, number> = {
  type_snippet: 24,
  type_prompt: 18,
  type_command: 15,
  type_note: 12,
  type_file: 5,
  type_image: 5,
  type_link: 8,
};
